---
- hosts: localhost
  roles:
    - role: tripleo-container-patch
      host_dir: "/usr/lib/python3.6/site-packages/neutron"
      container_dir: "/usr/lib/python3.6/site-packages/neutron"
      containers: ["neutron_l3_agent"]
      patches: ["648522"]
