---
- name: "Check {{ paunch_config }} exists"
  stat:
    path: "{{ container_cli }}"

- include_tasks: apply_patch.yaml
  with_items: patches

- name: Map directory including the patch into the container.
  become: True
  json_patch:
    src: "{{ paunch_config }}"
    operations:
      - op: add
        path: "/{{ item }}/volumes/-"
        value: "{{ host_dir }}:{{ container_dir }}:ro"
  loop: "{{ containers }}"

- block:
  - name: Remove the containers via docker
    docker_container:
      name: "{{ item }}"
      state: absent
    loop: "{{ containers }}"

  - name: Rebuild container with paunch
    command: "paunch debug --file {{ paunch_config }} --container {{ item }} --action run"
    loop: "{{ containers }}"

  become: True
  when: container_cli == "docker"

- block:
  - name: Stop systemd services
    service:
      name: "tripleo_{{ item }}"
      state: stopped
    loop: "{{ containers }}"

  - name: Remove the containers via podman
    command: "podman rm -f {{ item }}"
    loop: "{{ containers }}"

  - name: Rebuild container with paunch
    command: "paunch debug --file {{ paunch_config }} --container {{ item }} --action run"
    loop: "{{ containers }}"

  - name: Start systemd services
    service:
      name: "tripleo_{{ item }}"
      state: started
    loop: "{{ containers }}"
  become: True
  when: container_cli == "podman"

